version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./ssp:/app/ssp
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./.env:/app/.env
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - SSP_BASE=ssp
    restart: unless-stopped
    networks:
      - ssp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ssp-network:
    driver: bridge
